# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b1bc6eb254edcece86fd6cb15343134a2f5e6c3dd4673d235c107629b38b0779009b1a9a4b3e7510e648afa4b0b9ef504fdee00266ec00492716b16167ab60b

test:
  secret_key_base: b08fe31d9f4267d4f12c9231c9df010da853c977a108c10484e0b3a0ee95ae5cafd160bf785e72e599733174a4c30ebf0bec06730039ac6069585d3113b69dd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
