source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'pg', '~> 0.15'
gem 'slim-rails'
gem 'envied'

# authentication
gem 'omniauth'
gem 'omniauth-github'

# communication
gem 'faraday',            '~> 0.9.0'
gem 'faraday_middleware'

group :development, :test do
  # debugging
  gem 'pry-rails'
  gem 'pry-byebug'

  # development performance
  gem 'spring'

  # documentation
  gem 'annotate'
end
