source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'pg', '~> 0.15'
gem 'slim-rails'
gem 'envied'

# auth
gem 'omniauth'
gem 'omniauth-github'

group :development, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'spring'
end
